job "test" {
  type = "service"
  datacenters = ["dc1"]
  group "test" {
    count = 2
    task "spew" {
      driver = "exec"
      config {
        command = "spew"
        args    = ["XYZ"]
      }
      artifact {
        source = "https://github.com/mmcquillan/spew/releases/download/v0.1/spew.tar.gz"
      }
      env {
        SPEW_OUT = "testing nomad"
        SPEW_INTERVAL = "3s"
      }
    }
  }
}
