job "deploy-test" {
  type = "service"
  datacenters = ["dc1"]
  update {
    max_parallel     = 1
    stagger          = "10s"
    canary           = 1
  }
  group "deploy-test" {
    count = 3
    task "spew" {
      driver = "exec"
      config {
        command = "spew"
        args    = ["DEPLOY"]
      }
      artifact {
        source = "https://github.com/mmcquillan/spew/releases/download/v0.1/spew.tar.gz"
      }
      env {
        SPEW_OUT = "testing nomad deploys"
        SPEW_INTERVAL = "15s"
      }
    }
  }
}
