job "bad-parse" {
  type = "service"
  datacenters = ["dc1"]
  update {
    max_parallel     = 1
    stagger          = "10s"
  }
  group "bad-parse" {
    count = 3
    task "bad-parse" {
      driver = "exec"
      config {
        command = "spew"
        args    = ["ABC"]
      }
      artifact {
        source = "https://github.com/mmcquillan/spew/releases/download/v0.1/spew.tar.gz"
      }
      env {
        SPEW_OUT = "testing nomad"
        SPEW_INTERVAL = "3s"
      }
    }
  }
